python oldTFInput.py  BUF-AIV  Testinstances/A2-BUF_A2-AIV 
python oldTFInput.py  BUF-ANT  Testinstances/A2-BUF_A2-ANT 
python oldTFInput.py  BUF-BEE  Testinstances/A2-BUF_A2-BEE 
python oldTFInput.py  BUF-BOK  Testinstances/A2-BUF_A2-BOK 
python oldTFInput.py  BUF-EGL  Testinstances/A2-BUF_A2-EGL 
python oldTFInput.py  BUF-GNU  Testinstances/A2-BUF_A2-GNU 
python oldTFInput.py  BUF-JKL  Testinstances/A2-BUF_A2-JKL 
python oldTFInput.py  BUF-LEO  Testinstances/A2-BUF_A2-LEO 
python oldTFInput.py  BUF-NAS  Testinstances/A2-BUF_A2-NAS 
python oldTFInput.py  BUF-OWL  Testinstances/A2-BUF_A2-OWL 
python oldTFInput.py  BUF-ZEB  Testinstances/A2-BUF_A2-ZEB 
python oldTFInput.py  EGL-BEE  Testinstances/A2-EGL_A2-BEE 
python oldTFInput.py  EGL-GNU  Testinstances/A2-EGL_A2-GNU 
python oldTFInput.py  EGL-LEO  Testinstances/A2-EGL_A2-LEO 
python oldTFInput.py  GNU-BEE  Testinstances/A2-GNU_A2-BEE 
python oldTFInput.py  GNU-JKL  Testinstances/A2-GNU_A2-JKL 
python oldTFInput.py  GNU-LEO  Testinstances/A2-GNU_A2-LEO 
python oldTFInput.py  LEO-AIV  Testinstances/A2-LEO_A2-AIV 
python oldTFInput.py  LEO-ANT  Testinstances/A2-LEO_A2-ANT 
python oldTFInput.py  LEO-BEE  Testinstances/A2-LEO_A2-BEE 
python oldTFInput.py  LEO-BOK  Testinstances/A2-LEO_A2-BOK 
python oldTFInput.py  LEO-JKL  Testinstances/A2-LEO_A2-JKL 
python oldTFInput.py  LEO-NAS  Testinstances/A2-LEO_A2-NAS 
python oldTFInput.py  LEO-OWL  Testinstances/A2-LEO_A2-OWL 